### ISSUE TITLE
可以做一个纯前端识别二维码的小程序版本吗？

### ISSUE THREAD

**Issue by byenic** [sinchang/qrcode-parser#1]
现在小程序有些场景是离线的，但是需要扫码识别，希望可以纯前端支持！

**Comment by byenic** [comment]
好的，多谢！但是小程序没有图片URL的，只有一个临时存储的地址，也不能读取文件内容。您的接口我看了一下是重要传这两个参数，有没有可能穿临时存储地址，或者二维码图片的base64编码？

**Comment by sinchang** [comment]
小程序官方的 api [scanCode](https://developers.weixin.qq.com/miniprogram/dev/api/scancode.html) 需要联网才行？

**Comment by sinchang** [comment]
closed by 72b3d495a87ac7ffde03f83cb51a10ef14f66fb7
