### ISSUE TITLE
Decoding doesn't work on mobile browser

### ISSUE THREAD

**Issue by dakshshah96** [sinchang/qrcode-parser#2]
The decoding of a QR code uploaded in a file works on desktop browsers but doesn't work on mobile browsers (Android Chrome, iOS Safari or iOS Chrome).

Are these browsers not supported or is there something wrong that I'm doing?

Thanks.

**Comment by sinchang** [comment]
you should upload image only type is `image/png`

ref: https://github.com/photopea/UPNG.js/issues/13#issuecomment-346581092
